### ISSUE TITLE
Error: Error exchanging code for data: 401 Unauthorized

### ISSUE THREAD

**Issue by wirelessjeano** [civicteam/npm-civic-sip-api#18] opened 2018-05-11 17:47 UTC
Hi all,

I am having an issue with the Civic node package and I am wondering if the issue is on my side or yours. I have double checked all of my credentials and even regenerated my tokens.

civicproxy_1     | appId = BJLbJEmRf
civicproxy_1     | prvKey = 0a26dbf45406d9e7c946af67f7d5afc34665ce7e3ec3e227fdd62c9b540a9add
civicproxy_1     | appSecret = 6c02c5fb6ad2bd0b241f6e471ac4b8b9
civicproxy_1     | authtoken = eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYTc3NDRmZS00NjI3LTRlYjgtOTVkYi00NDY2ZTRkYTUyOGIiLCJpYXQiOjE1MjYwNjA0MzAuOTg5LCJleHAiOjE1MjYwNjIyMzAuOTg5LCJpc3MiOiJjaXZpYy1zaXAtaG9zdGVkLXNlcnZpY2UiLCJhdWQiOiJodHRwczovL2FwaS5jaXZpYy5jb20vc2lwLyIsInN1YiI6IkJKTGJKRW1SZiIsImRhdGEiOnsiY29kZVRva2VuIjoiOWFkNzk5MWUtZjE2ZC00MzcxLTg2OTktM2I0ZWQxM2QxOWRkIn19.nDN8E9C1KsXxTUxqgeWtlgmBF3HrWpM7w5Ltll6iKJ_JFN5rh7wCVZayNB9Rp2tGp-gt5NsNal38GS3NhHLSeA
civicproxy_1     | Error: Error exchanging code for data: 401 Unauthorized
civicproxy_1     |     at needle.then.catch (/app/node_modules/civic-sip-api/index.js:167:15)
civicproxy_1     |     at <anonymous>
civicproxy_1     |     at process._tickCallback (internal/process/next_tick.js:182:7)

Any help would be greatly appreciated!

**Comment by slaphead** [comment] 2018-05-11 18:02
Hi @wirelessjeano,

Could you provide the lines of code where you are calling exchangeToken please? We just need to see what you are passing in on the server side when making the call. Can you also show the config you are passing in when instantiating the sip client. (No need to show the key values, just the structure)

Lastly, we do not recommend showing your appSecret or prvKey to anyone. So please go ahead and regenerate the keys again so the ones you have shown here are no longer valid.

**Comment by slaphead** [comment] 2018-05-11 20:46
I also checked the logs and it seems to be an issue with the token that is being passed in. The code itself looks fine. Thank you for sharing that.

Normally this can occur in a misconfiguration where the secret and/or the private key is not correct. The thing is here you have regenerated them and still got the same issue.

On the client side, are you getting the qr code, scanning, waiting for the jwtToken that is returned during the polling i.e. the event auth-code-received

```
// Listen for data
  civicSip.on('auth-code-received', function (event) {
    // encoded JWT Token is sent to the server
    var jwtToken = event.response;

    // Your function to pass JWT token to your server
    sendAuthCode(jwtToken);
  });
```

and sending the token in there back to your server? I just need to double check the flow with you.

I tested quickly with a basic flow like yours using other credentials and it worked ok. So I can confirm the exchange itself works ok. My only thought right now is there is something wrong with the authToken after it gets to your server.

**Comment by wirelessjeano** [comment] 2018-05-11 22:13
Thats exactly what I am doing. 

My client side code is:

 <script src="https://hosted-sip.civic.com/js/civic.sip.min.js"></script>
    <script>
        var civicSip = new civic.sip({ appId: 'BJLbJEmRf' });
        var button = document.querySelector('#civicLogin');
        button.addEventListener('click', function () {
            civicSip.signup({ style: 'popup', scopeRequest: civicSip.ScopeRequests.BASIC_SIGNUP });
        });
        
        civicSip.on('auth-code-received', function (event) {
            var jwtToken = event.response;
            $.ajax({
                url: 'account/civic',
                dataType: 'json',
                type: 'post',
                contentType: 'application/json',
                data: JSON.stringify({ "authCode": jwtToken }),
                statusCode: {
                    200: function (response) {
                        // do your stuff here
                        console.log("Success!");
                        //location.reload();
                    }
                }
            });
        });
        
        // Error events.
        civicSip.on('civic-sip-error', function (error) {
            // handle error display if necessary.
            console.log('   Error type = ' + error.type);
            console.log('   Error message = ' + error.message);
        });
    </script>

My server side code is:

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Civic([FromBody] CivicAuthModel model)
        {
            if (string.IsNullOrWhiteSpace(model?.authToken)) return BadRequest();
            
            var civicJsonData = JsonConvert.SerializeObject(new { authtoken = model.authToken });

            var civicProxyUrl = _configuration["AppSettings:CivicProxyUrl"];
            
            var httpWebRequest = (HttpWebRequest)WebRequest.Create(civicProxyUrl);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                streamWriter.Write(civicJsonData);
                streamWriter.Flush();
                streamWriter.Close();
            }

            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();

        ......

My original credentials that failed today were working correctly yesterday.

**Comment by slaphead** [comment] 2018-05-11 22:41
Ok then I will need to test with the credentials created on your account specifically. If you are ok with this, can you create a new app in the integration portal and send through the secret, prvKey and appId. I will test with those credentials, then once confirmed you can test with them too.

Once complete you can just delete the app we used to test this.

**Comment by wirelessjeano** [comment] 2018-05-11 22:57
Hi

I just installed the latest Apple updates and restarted my Mac - it started working! Thanks for your help and sorry for being a noob. :o

**Comment by slaphead** [comment] 2018-05-14 18:46
Hey @wirelessjeano , I am glad it is working! I hope it was just a config error. I will close this for now. Happy coding!

**Closed by slaphead** 2018-05-14 18:46 UTC
